### ISSUE TITLE
Error logging in using GitHub

### ISSUE THREAD

**Issue by vmadman** [containership/containership.plugin.cloud#107]
I will try to figure this out and submit a PR if I find a few minutes to do so, but, just in case someone is able to beat me to it .. I wanted to go ahead and report this, here:

```
$ cs cloud login github

Username: myusername
Password:

/root/.containership/plugins/node_modules/containership.plugin.cloud/lib/cli.js:71
                        return callback(new Error('Error generating ContainerShip auth token'));
                               ^

TypeError: callback is not a function
    at Request.request [as _callback] (/root/.containership/plugins/node_modules/containership.plugin.cloud/lib/cli.js:71:32)
    at Request.self.callback (/root/.containership/plugins/node_modules/containership.plugin.cloud/node_modules/request/request.js:360:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/.containership/plugins/node_modules/containership.plugin.cloud/node_modules/request/request.js:1202:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/.containership/plugins/node_modules/containership.plugin.cloud/node_modules/request/request.js:1150:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

I ran this command _immediately_ after installing `cs` using:

```
$ npm install -g containership
$ cs plugin add cloud
```

Also, fyi ..

```
$ node -v
v6.9.4

$ npm -v
3.10.10

$ cs -v
v1.8.1-hotfix-1
```

**Comment by nicktate** [comment]
@vmadman Will take a look into this ASAP. Thanks for the info.

**Comment by nicktate** [comment]
I think I see the problem. Going to patch and run a few tests internally and if it looks good I will cut a new release shortly and ping you. @vmadman

**Comment by nicktate** [comment]
Fixed in https://github.com/containership/containership.plugin.cloud/commit/c1c397d699dd89f3904fd1fac6ab17675e7173f2

If you re-run `cs plugin add cloud` it should resolve your issues.

Thanks for reporting the bug! @vmadman
