### ISSUE TITLE
Error when executing "use-cluster"

### ISSUE THREAD

**Issue by vmadman** [containership/containership.plugin.cloud#83]
With a fresh install of `containership` and `containership.plugin.cloud`, I hit an error when calling `use-cluster` for the first time...

```
$ node -v
v6.9.1

$ npm -v
3.10.8

$ npm install -g containership
...

$ cs -v
v1.7.1

$ cs plugin add cloud
...

$ cs cloud use-cluster 17ae8650-abc1-2345-941c-09aaa4224b91
/root/.containership/plugins/node_modules/containership.plugin.cloud/lib/cli.js:395
            config.config.headers['x-containership-cloud-cluster'] = options['cluster-id'];
                                                                   ^

TypeError: Cannot set property 'x-containership-cloud-cluster' of undefined
    at Object.callback [as cb] (/root/.containership/plugins/node_modules/containership.plugin.cloud/lib/cli.js:395:68)
    at Object.parse (/usr/lib/node_modules/containership/node_modules/nomnom/nomnom.js:302:15)
    at Object.<anonymous> (/usr/lib/node_modules/containership/index.js:110:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

(Yes, I installed it as `root`, but its a Vagrant box.. so.. security is not a major concern for me in this case)

I made a quick and easy edit in `lib/cli.js` which seemed to fix the problem.  I am going to submit a PR in a few minutes.

**Comment by vmadman** [comment]
Self-closing this issue in favor of #84.
